### ISSUE TITLE
KNOWLEDGE-BASE ISSUES

### ISSUE THREAD

**Issue by h0x0er** [h0x0er/kb_setup#86]
## Missing KBs

**Comment by h0x0er** [comment]
- [ ] [KB] Add GitHub token permissions for actions/configure-pages Action
  <details>
  <summary>Analysis</summary>

  ### Analysis
  ```yml
  Action Name: actions/configure-pages
  Action Type: Node
  GITHUB_TOKEN Matches: token
  Top language: JavaScript
  Stars: 41
  Private: false
  Forks: 14
  ```
  ### Endpoints Found
  |Endpoint | Permission|
  |---------| ----------|
  
  #### FollowUp Links.
  https://github.com/actions/configure-pages/blob/404d23c4a6f35881831e332b4d8c5a3f7ef487f5/src/api-client.test.js
  https://github.com/actions/configure-pages/blob/c3113876b026427bdadec0ea1ed8997d042b09ad/src/api-client.js
  https://github.com/actions/configure-pages/blob/15f519fab9b615b894b202620f4be660521e4055/src/context.js
  https://github.com/actions/configure-pages/blob/27457957e6c812e8ba898b5956c836f663da7dde/src/index.js
  
  ### action-security.yml
  ```yaml
  name: 'Configure GitHub Pages'
  github-token:
    action-input:
      input: token
      is-default: true
    permissions:
  ```
  
  </details>
- [ ] [KB] Add KB for potiuk/cancel-workflow-runs
  <details>
  <summary>Analysis</summary>

  ### Analysis
  ```yml
  Action Name: potiuk/cancel-workflow-runs
  Action Type: Node
  GITHUB_TOKEN Matches: token,GITHUB_TOKEN
  Top language: TypeScript
  Stars: 30
  Private: false
  Forks: 5
  ```
  ### Endpoints Found
  |Endpoint | Permission|
  |---------| ----------|
  pulls.list | read
  actions.cancelWorkflowRun | write
  actions.getWorkflow | read
  actions.getWorkflowRun | read
  actions.listJobsForWorkflowRun | read
  actions.listWorkflowRuns | read
  issues.create | write
  issues.createComment | write
  
  #### FollowUp Links.
  https://github.com/potiuk/cancel-workflow-runs/blob/953e057dc81d3458935a18d1184c386b0f6b5738/src/main.ts
  
  ### action-security.yml
  ```yaml
  name: 'Cancel Workflow Runs'
  github-token:
    action-input:
      input: token
    permissions:
      pull-requests: read
      actions: write
      issues: write
  ```
  
  </details>

- [ ] [KB] Add KB for lewagon/wait-on-check-action
  <details>
  <summary>Analysis</summary>

  ### Analysis
  ```yml
  Action Name: lewagon/wait-on-check-action
  Action Type: Composite
  GITHUB_TOKEN Matches: repo-token,GITHUB_TOKEN,TOKEN,token,REPO_TOKEN
  Stars: 121
  Private: false
  Forks: 18
  ```
  </details>

- [ ] [KB] Add KB for gaurav-nelson/github-action-markdown-link-check
  <details>
  <summary>Analysis</summary>

  ### Analysis
  ```yml
  Action Name: gaurav-nelson/github-action-markdown-link-check
  Action Type: Docker
  GITHUB_TOKEN Matches: token
  Stars: 242
  Private: false
  Forks: 49
  ```
  </details>
